<%@ Page Title="" Language="C#" MasterPageFile="~/TrollUniversity.Master" AutoEventWireup="true" CodeBehind="Student View.aspx.cs" Inherits="Assignment_4.WebForm2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    Student Filter (Last Name):
    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
        ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Students]"
        FilterExpression="LastName LIKE '{0}'" UpdateCommand="UPDATE [Students] SET [LastName] =@LName, [FirstName] =@FName, [MiddleInitial] =@MInit, [Phone] =@Phone, [GPA] =@GPA WHERE [Email]=@Email">
        <FilterParameters>
            <asp:ControlParameter
                Name="LastName"
                ControlID="TextBox1"
                PropertyName="Text" />
        </FilterParameters>
        <UpdateParameters>

        </UpdateParameters>
    </asp:SqlDataSource>
    <hr />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Email" DataSourceID="SqlDataSource2" AllowPaging="True" AllowSorting="True" AutoGenerateSelectButton="True" GridLines="Horizontal" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="LastName" HeaderText="Last Name" SortExpression="LastName" />
            <asp:BoundField DataField="FirstName" HeaderText="First Name" SortExpression="FirstName" />
            <asp:BoundField DataField="MiddleInitial" HeaderText="Middle Initial" SortExpression="MiddleInitial" />
            <asp:BoundField DataField="Phone" HeaderText="Phone" SortExpression="Phone" />
            <asp:BoundField DataField="Email" HeaderText="Email" ReadOnly="True" SortExpression="Email" />
            <asp:BoundField DataField="GPA" HeaderText="GPA" SortExpression="GPA" />
        </Columns>
    </asp:GridView>
</asp:Content>
